API-6700: updated code to compile with Scala 2.13 and scalafix, scala…
hmrc/api-platform-xml-services pull request #43
Opened 2023-05-15 11:54 UTC by mattclark-zerogravit

…fmt changes.

2023-05-15 15:22 UTC, johnsgp submitted a review, later dismissed

2023-05-16 06:50 UTC, AndySpaven commented on it/uk/gov/hmrc/apiplatformxmlservices/repository/OrganisationRepositoryISpec.scala
> +    def getUuid: UUID = UUID.randomUUID()
Probably begging to use to the UserId.random() approach - I'm guessing no domain lib here (I know it wont be)

2023-05-16 06:51 UTC, AndySpaven commented on it/uk/gov/hmrc/apiplatformxmlservices/repository/OrganisationRepositoryISpec.scala
> +    def getUuid: UUID = UUID.randomUUID()
getUUID is not pure so probably should have () but moot if it's not used at all.

2023-05-16 06:52 UTC, AndySpaven commented on it/uk/gov/hmrc/apiplatformxmlservices/repository/OrganisationRepositoryISpec.scala
> +    def createOrganisations = {
It's side effecting so probably should retain () here and at call sites

2023-05-16 06:53 UTC, AndySpaven commented on it/uk/gov/hmrc/apiplatformxmlservices/repository/OrganisationRepositoryISpec.scala
> +    def getUuid: UUID = UUID.randomUUID()
Or maybe it can be considered enough to loose the (). 🤷‍♂️

2023-05-16 06:57 UTC, AndySpaven commented on it/uk/gov/hmrc/apiplatformxmlservices/support/MetricsTestSupport.scala
> +    for (metric <- asScala[String](registry.getMetrics.keySet().iterator())) {
It should be possible to postfix this rather than invoking as a method call.

2023-05-16 06:59 UTC, AndySpaven commented on test/uk/gov/hmrc/apiplatformxmlservices/controllers/OrganisationControllerSpec.scala
> +    val orgOne: OrganisationWithNameAndVendorId = OrganisationWithNameAndVendorId(name = OrganisationName("OrgOne"), vendorId = VendorId(1))
Something is putting types in in some places and removing them in others.

2023-05-16 07:01 UTC, AndySpaven requested changes
Some comment

2023-05-16 13:32 UTC, AndySpaven commented on app/uk/gov/hmrc/apiplatformxmlservices/models/models.scala
> +  def random: OrganisationId = OrganisationId(UUID.randomUUID())
Thinking about 2.13 - these should probably be () as they do something (but not a side effect - a constructed value returned).  torn both ways on this.

2023-05-16 13:32 UTC, AndySpaven approved these changes

2023-05-16 14:11 UTC, mattclark-zerogravit commented on test/uk/gov/hmrc/apiplatformxmlservices/controllers/OrganisationControllerSpec.scala
> +    val orgOne: OrganisationWithNameAndVendorId = OrganisationWithNameAndVendorId(name = OrganisationName("OrgOne"), vendorId = VendorId(1))
Sorted

2023-05-16 14:11 UTC, mattclark-zerogravit commented on it/uk/gov/hmrc/apiplatformxmlservices/repository/OrganisationRepositoryISpec.scala
> +    def createOrganisations = {
Sorted

2023-05-16 14:11 UTC, mattclark-zerogravit commented on it/uk/gov/hmrc/apiplatformxmlservices/repository/OrganisationRepositoryISpec.scala
> +    def getUuid: UUID = UUID.randomUUID()
Yep sorted

2023-05-16 14:12 UTC, mattclark-zerogravit commented on it/uk/gov/hmrc/apiplatformxmlservices/repository/OrganisationRepositoryISpec.scala
> +    def getUuid: UUID = UUID.randomUUID()
Sorted

2023-05-16 14:12 UTC, mattclark-zerogravit commented on app/uk/gov/hmrc/apiplatformxmlservices/models/models.scala
> +  def random: OrganisationId = OrganisationId(UUID.randomUUID())
Sorted

2023-05-16 18:22 UTC, merged